version: '3.8'

services:
  web:
    build: .
    container_name: calorie-tracker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: >
      sh -c "python calorie_tracker/manage.py migrate &&
             python calorie_tracker/manage.py runserver 0.0.0.0:8000"
