# Generated by Django 3.2.25 on 2025-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('date_consumed', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Food Entries',
                'ordering': ['-date_consumed', 'food_name'],
            },
        ),
    ]
